### ISSUE TITLE
StringIIOBE thrown

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [kabacinsp/magicnumbers#1]
Session log:

```
[tammo@lafk-T470 magicnumbers]$ java CheckFile                                                                                                   [INSERT]
Write file path
cos.gif
gif
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: begin 0, end 6, length 5
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at IfGIF.<init>(IfGIF.java:31)
	at CheckFile.main(CheckFile.java:35)
[tammo@lafk-T470 magicnumbers]$ java CheckFile                                                 [INSERT]
Write file path
ancd.txt
txt
This is TXT file
```

**Comment by kabacinsp** [comment]
The error was corrected by adding a condition
(lenGIF > 6 && (gifFile.substring(0, 6).equals("GIF89a") || gifFile.substring(0, 6).equals("GIF87a"))
